# Generated by Django 4.1.4 on 2022-12-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='shipping',
        ),
    ]
