# Generated by Django 4.1.4 on 2022-12-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_digital_product_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping',
            new_name='digital',
        ),
    ]
