# Generated by Django 4.1.4 on 2022-12-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_shipping_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='ship',
        ),
    ]
